src/ThoughtBundle/Entity/Comment.php
<?php

namespace ThoughtBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Comment
 *
 * @ORM\Entity(repositoryClass="ThoughtBundle\Repository\CommentRepository")
 * @ORM\Table(name="comment")
 * @ORM\HasLifecycleCallbacks()
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(name="email", type="string")
     */
    protected $email;

    /**
     * @ORM\Column(name="text", type="text")
     */
    protected $text;

    /**
     * @ORM\ManyToOne(targetEntity="ThoughtBundle\Entity\Thought", inversedBy="comments")
     * @ORM\JoinColumn(name="thought_id", referencedColumnName="id")
     */
    protected $thought;

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * Get ful name $name + email
     *
     * @return string
     */
    public function getFullName()
    {
        $name  = $this->name;
        $email = $this->email;

        return (!empty($name) ? $name . ', ' : '') . $email;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Comment
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Comment
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set text
     *
     * @param string $text
     *
     * @return Comment
     */
    public function setText($text)
    {
        $this->text = $text;

        return $this;
    }

    /**
     * Get text
     *
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Comment
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set thought
     *
     * @param \ThoughtBundle\Entity\Thought $thought
     *
     * @return Comment
     */
    public function setThought(\ThoughtBundle\Entity\Thought $thought = null)
    {
        $this->thought = $thought;

        return $this;
    }

    /**
     * Get thought
     *
     * @return \ThoughtBundle\Entity\Thought
     */
    public function getThought()
    {
        return $this->thought;
    }
}

src/ThoughtBundle/Entity/Thought.php
<?php

namespace ThoughtBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="ThoughtBundle\Repository\ThoughtRepository")
 * @ORM\Table(name="thought")
 * @ORM\HasLifecycleCallbacks
 */
class Thought
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="text")
     */
    protected $content;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $tags;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="text")
     */
    protected $category;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $thoughtInfo;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="text")
     */
    protected $author;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $updateAt;

    /**
     * @ORM\Column(type="integer")
     */
    protected $amount = 0;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $published;

    /**
     * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User", inversedBy="thoughts")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $owner;

    /**
     * @var ArrayCollection|Like[]
     *
     * @ORM\OneToMany(targetEntity="ThoughtBundle\Entity\Like", mappedBy="thought", cascade={"persist"})
     */
    protected $likes;

    /**
     * @var Integer
     * @ORM\Column(type="integer")
     */
    protected $likesCount = 0;

    /**
     * @ORM\OneToMany(targetEntity="ThoughtBundle\Entity\Comment", mappedBy="thought", orphanRemoval=true)
     */
    protected $comments;

    /**
     * @ORM\OneToMany(targetEntity="ThoughtBundle\Entity\ThoughtChain", mappedBy="thought", orphanRemoval=true)
     */
    protected $chainThoughts;

    /**
     * @var ArrayCollection|WatchedThought[]
     *
     * @ORM\OneToMany(targetEntity="ThoughtBundle\Entity\WatchedThought", mappedBy="thought")
     */
    protected $watchedThoughts;

    /**
     * @var ArrayCollection|ThoughtRelated[]
     * @ORM\OneToMany(targetEntity="ThoughtBundle\Entity\ThoughtRelated", mappedBy="thought", orphanRemoval=true)
     */
    protected $relatedThoughts;

    /**
     * @var ArrayCollection|ThoughtRelated[]
     * @ORM\OneToMany(targetEntity="ThoughtBundle\Entity\ThoughtRelated", mappedBy="relatedThought", orphanRemoval=true)
     */
    protected $inverseRelatedThoughts;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->likes    = new ArrayCollection();
        $this->relatedThoughts = new ArrayCollection();
        $this->inverseRelatedThoughts = new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getOwnerStudent()
    {
        if ($this->getOwner() !== null) {
            return in_array('ROLE_STUDENT', $this->getOwner()->getRoles());
        }
        return false;
    }

    /**
     * @return int
     */
    public function getLikesCount(): int
    {
        return $this->likesCount;
    }

    public function getTotalLikes()
    {
        return $this->likesCount + count($this->likes);
    }

    /**
     * @param int $likesCount
     */
    public function setLikesCount(int $likesCount): void
    {
        $this->likesCount = $likesCount;
    }

    public function incrementLikeCount(): void
    {
        $this->likesCount++;
    }

    public function reduceLikeCount(): void
    {
        if ($this->likesCount > 0) {
            $this->likesCount--;
        }
    }


    /**
     * Set content
     *
     * @param string $content
     *
     * @return Thought
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set tags
     *
     * @param string $tags
     *
     * @return Thought
     */
    public function setTags($tags)
    {
        $tags       = preg_replace('/\,/', ' , ', $tags);
        $this->tags = $tags;

        return $this;
    }

    /**
     * Get tags
     *
     * @return string
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Set category
     *
     * @param string $category
     *
     * @return Thought
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set thoughtInfo
     *
     * @param string $thoughtInfo
     *
     * @return Thought
     */
    public function setThoughtInfo($thoughtInfo)
    {
        $this->thoughtInfo = $thoughtInfo;

        return $this;
    }

    /**
     * Get thoughtInfo
     *
     * @return string
     */
    public function getThoughtInfo()
    {
        return $this->thoughtInfo;
    }

    /**
     * Set author
     *
     * @param string $author
     *
     * @return Thought
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Thought
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updateAt
     *
     * @param \DateTime $updateAt
     *
     * @return Thought
     */
    public function setUpdateAt($updateAt)
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    /**
     * Get updateAt
     *
     * @return \DateTime
     */
    public function getUpdateAt()
    {
        return $this->updateAt;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * @ORM\PrePersist
     */
    public function setPublishedValue()
    {
        if (!$this->published) {
            $this->published = false;
        }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdateAtValue()
    {
        $this->updateAt = new \DateTime();
    }

    /**
     * @ORM\PreFlush
     */
    public function setAmountValue()
    {
        $charList = preg_replace('/\s|"|\?|\.|,/', '', $this->content);

        $this->amount = str_word_count($this->content, 0, $charList);
    }

    /**
     * Set published
     *
     * @param bool $published
     *
     * @return Thought
     */
    public function setPublished($published)
    {
        $this->published = $published;

        return $this;
    }

    /**
     * Get published
     *
     * @return bool
     */
    public function getPublished()
    {
        return $this->published;
    }

    /**
     * @return bool
     */
    public function isPublish()
    {
        return $this->published ? true : false;
    }

    /**
     * Set amount
     *
     * @param int $amount
     *
     * @return Thought
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * Get amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set owner
     *
     * @param \Application\Sonata\UserBundle\Entity\User $owner
     *
     * @return Thought
     */
    public function setOwner(\Application\Sonata\UserBundle\Entity\User $owner = null)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Get owner
     *
     * @return \Application\Sonata\UserBundle\Entity\User
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @return mixed
     */
    public function getLikes()
    {
        return $this->likes;
    }

    public function getLiked()
    {
        return $this->likes;
    }

    public function addLike($like)
    {
//        if (!$this->likes) {
//            $this->likes = new ArrayCollection();
//        }
        $this->likes->add($like);
    }

    /**
     * Add comments
     *
     * @param \ThoughtBundle\Entity\Comment $comments
     *
     * @return Thought
     */
    public function addComment(\ThoughtBundle\Entity\Comment $comments)
    {
        $this->comments[] = $comments;

        return $this;
    }

    /**
     * Remove comments
     *
     * @param \ThoughtBundle\Entity\Comment $comments
     */
    public function removeComment(\ThoughtBundle\Entity\Comment $comments)
    {
        $this->comments->removeElement($comments);
    }

    /**
     * Get comments
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * Add chainThoughts
     *
     * @param \ThoughtBundle\Entity\ThoughtChain $chainThoughts
     *
     * @return Thought
     */
    public function addChainThought(\ThoughtBundle\Entity\ThoughtChain $chainThoughts)
    {
        $this->chainThoughts[] = $chainThoughts;

        return $this;
    }

    /**
     * Remove chainThoughts
     *
     * @param \ThoughtBundle\Entity\ThoughtChain $chainThoughts

src/ThoughtBundle/Resources/views/author.html.twig
{% extends 'ThoughtBundle::layout.html.twig' %}

{% block page_title %}Les fils de la pensée{% endblock %}

{% block content %}
     {% set search = app.request.get('search') %}
    {% set is_fields = search.field is defined ? true : false %}
    <form method="get" xmlns="http://www.w3.org/1999/html">
        <div class="col-md-12">
            <div class="row">
                <div class="form-group col-sm-12 alphas">
                    {{ range('A', 'Z')|alphabetAuthersLinks}}
                </div>
            </div>
            {% if thoughts is defined %}
                <div class="row">
                    <div class="col-sm-6">{{ 'thought.filter.result_counter'|trans }}: {{ thoughts.getTotalItemCount() }}</div>
                    <div class="col-sm-6 text-right">{{ 'thought.filter.time_counter'|trans }}: {{ timeExecute|round(4) }}s</div>
                </div>

                <div class="navigation text-center">
                    {{ knp_pagination_render(thoughts) }}
                </div>

                {% for thought in thoughts %}
                    {{ include('@Thought/quoteLayout.html.twig', {'thought': thought}) }}
                {% else %}

                {% endfor %}

                <div class="navigation text-center">
                    {{ knp_pagination_render(thoughts) }}
                </div>
            {% elseif authors %}
                <div class="row">
                    <div class="col-sm-6">{{ 'thought.filter.result_counter'|trans }}: {{ authors.getTotalItemCount() }}</div>
                    <div class="col-sm-6 text-right">{{ 'thought.filter.time_counter'|trans }}: {{ timeExecute|round(4) }}s</div>
                </div>

                <div class="navigation text-center">
                    {{ knp_pagination_render(authors) }}
                </div>

                {% for author in authors %}
                    {{ include('@Thought/authorLayout.html.twig', {'author': author}) }}
                {% else %}

                {% endfor %}

                <div class="navigation text-center">
                    {{ knp_pagination_render(authors) }}
                </div>

            {% endif %}
        </div>
    </form>

{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {

            $('p.quote_title').on('click', 'a.author_name', function (){
                $(this).parents('.jumbotron').find('div.dropdown').slideToggle();
            });

        });

    </script>
{% endblock %}

src/ThoughtBundle/Resources/views/content.html.twig
{% extends 'ThoughtBundle::layout.html.twig' %}

{% block page_title %}{{ content.title }}{% endblock %}

{% block content %}
    <h1>{{ content.title }}</h1>
    {{ content.content|raw }}
{% endblock %}

src/ThoughtBundle/Resources/views/quoteLayout.html.twig
<div class="jumbotron quote" data-quote="{{ thought.id }}">

    {% if app.user %}
        {% if app.user.role == 'ROLE_STUDENT' or app.user.role == 'ROLE_TEACHER' %}
            {% if thought.owner.role is defined  %}
                {% if thought.owner.role == 'ROLE_STUDENT' or thought.owner.role == 'ROLE_TEACHER' %}
                    <span class="thought-lable label label-warning">Véritable Cination non validée</span>
                {% endif %}
            {% endif %}
        {% endif %}
    {% endif %}

    {% set already_chains = [] %}
    {% for arr_chain in thought.chainThoughts %}
        {% set already_chains = already_chains|merge([{name: arr_chain.chain.name, id: arr_chain.chain.id}]) %}
    {% endfor %}

    <p class="quote_title">
        <span>
            <a href="{{ path('thought_homepage_index', {'search[words]': thought.category, 'search[field][category]': 'on', 'search[strict]': 'on'}) }}">
                {{ thought.category }}
            </a>
        </span>

        {% if app.user %}
            {% set editThought = false %}
            {% if thought.owner is defined and thought.owner is not null %}
                {% if thought.owner.id == app.user.id %}
                    {% set editThought = true %}
                {% endif %}
            {% endif %}

            {% if is_granted('ROLE_MODERATOR') %}
                <span class="quote_edit">
                        <a href="{{ path('admin_thought_thought_edit', {'id': thought.id}) }}">
                            {{ 'user.thought.list_page.link.edit'|trans }}
                        </a>
                    </span>
            {% elseif editThought%}
                <span class="quote_edit">
                        <a href="{{ path('sonata_user_thought_edit', {'id': thought.id}) }}">
                            {{ 'user.thought.list_page.link.edit'|trans }}
                        </a>
                    </span>
            {% endif %}
        {% endif %}

    </p>

    <div class="cke_no_bootstrap">
        <p class="quote_content">
            <span>{{ thought.content|customTag|raw|nl2br }}</span>
        </p>
    </div>
    <p>
        <strong>{{ 'thought.property.author'|trans|capitalize }}:</strong>
        <span class="author">
            <a href="{{ path('thought_homepage_index', {'search[words]': thought.author, 'search[filter_open]': '', 'search[field][author]': 'on', 'search[sorting]': ''}) }}">
                {{ thought.author }}
            </a>
        </span>

        {% set author = thought.author|authorsInfo %}
    </p>

    {% if author and (author.birthDate or author.country or author.sex or author.job or author.continent) %}
        <div class="authors_info" style="display: none;">

            <p><strong>{{ 'author.filter.fields.birthDate.label'|trans }}:</strong> <span>{{ author.birthDate }}</span></p>
            <p><strong>{{ 'author.filter.fields.country.label'|trans }}:</strong> <span>{{ author.country }}</span></p>
            <p><strong>{{ 'author.filter.fields.sex.label'|trans }}:</strong> <span>{{ author.sex }}</span></p>
            <p><strong>{{ 'author.filter.fields.job.label'|trans }}:</strong> <span>{{ author.job }}</span></p>
            <p><strong>{{ 'author.filter.fields.continent.label'|trans }}:</strong> <span>{{ author.continent }}</span></p>
        </div>
    {% endif %}

    <p>
        <strong>{{ 'thought.property.thoughtInfo'|trans|capitalize }}:</strong>
        <span>{{ thought.thoughtInfo }}</span>
    </p>
    <p class="quote_tags">
            <span>
                {% for tag in thought.tags|split(' , ') %}
                    {% if tag|trim|length > 0 %}
                        [<a href="{{ path('thought_homepage_index', {'search[words]': tag, 'search[field][tags]': 'on'}) }}">
                        <span>{{ tag }}</span>
                    </a>]
                    {% endif %}
                {% endfor %}
            </span>
    </p>

    {#  button like and comment  #}
    <div class="quote_row">
        <div>
            {% set liked = thought.likes %}
            <button class="btn btn-info btn-sm like-quote" data-quote="{{ thought.id }}" type="button">
            <span data-toggle="tooltip" data-html="true" data-placement="bottom" title="{{ include('ThoughtBundle::also_liked_tooltip.html.twig') }}">
                <span class="badge-text">
                    {{ liked ? 'thought.property.liked'|trans : 'thought.property.like'|trans }}
                </span> <span class="badge" style="display: {{ (thought.totalLikes > 0) ? 'inline-block' : 'none' }}">{{ thought.totalLikes }}</span>
            </span>
            </button>
        </div>
        &nbsp;
        <div>
            {% if app.request.get('thoughtId') == null %}
                <a class="page_quote_button btn btn-info btn-sm" href="{{ path('thought_thoughtpage_index', {'thoughtId': thought.id}) }}">
                    {{ 'thought.comment.page_quote'|trans }}
                </a>
            {% endif %}
        </div>
        &ensp;
        <div>
            {% if app.user %}
                <form></form>
                <form id="bind-thoughts-form" class="form-inline" action="{{ path('link-quotes') }}" method="post" >
                    <input type="hidden" name="thought_id" value="{{ thought.id }}" />
                    <input type="number" class="form-control"  name="thoughtRelated_id" value="" placeholder="Quote ID" />
                    <a class="send_id_for_related btn btn-info btn-sm">Lier une citation</a>
                </form>
            {% endif %}
        </div>
    </div>

    {# This! This is not ok! This is vary bad сode! #}
    {% set relatedThoughtCount = 0 %}
    {% for thought in thought.relatedThoughts %}
        {% if userFriends[thought.owner.id] is defined  %}
            {% set relatedThoughtCount = +1 %}
        {% endif %}
    {% endfor %}
    {% for thought in thought.inverseRelatedThoughts %}
        {% if userFriends[thought.owner.id] is defined  %}
            {% set relatedThoughtCount = +1 %}
        {% endif %}
    {% endfor %}


    <div class="quote_row">
        {% if app.user and relatedThoughtCount > 0 %}
            <div class="related-thoughts-block">
                <a class="related-thoughts-label">Citations liées:</a>
                <div class="related-thoughts">
                    {% for relatedThought in thought.relatedThoughts %}
                        {% if userFriends[relatedThought.owner.id] is defined  %}
                            <span>
                                <a href="{{ path('thought_thoughtpage_index', {'thoughtId': relatedThought.relatedThought.id}) }}">
                                    {{ relatedThought.relatedThought.category }} ({{ userFriends[relatedThought.owner.id] }})
                                </a>
                                {% if relatedThought.owner == app.user  %}
                                    &ensp;
                                    <a href="{{ path('unlink-quotes', {'thoughtRelatedId': relatedThought.id}) }}"
                                       class="message-button"
                                       data-toggle="tooltip"
                                       title="Remove relation"
                                       style="font-size: 12px"
                                    >
                                        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                                    </a>
                                {% endif %}
                            </span>
                        {% endif %}
                    {% endfor %}
                    {% for inverseThought in thought.inverseRelatedThoughts %}
                        {% if userFriends[inverseThought.owner.id] is defined  %}
                            <span>
                                <a href="{{ path('thought_thoughtpage_index', {'thoughtId': inverseThought.thought.id}) }}">
                                    {{ inverseThought.thought.category }} ({{ userFriends[inverseThought.owner.id] }})
                                </a>
                                {% if inverseThought.owner == app.user  %}
                                    &ensp;
                                    <a href="{{ path('unlink-quotes', {'thoughtRelatedId': inverseThought.id}) }}"
                                       class="message-button"
                                       data-toggle="tooltip"
                                       title="Remove relation"
                                       style="font-size: 12px"
                                    >
                                        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                                    </a>
                                {% endif %}
                            </span>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {#  Mis dans la chaine  #}
        <div class="put-in-chain">
            {% if already_chains|length %}
                {% set template = '@Thought/include/chainsTooltip.html.twig'  %}
                <span class="is-added pull-right hastooltip" data-toggle="tooltip" data-placement="bottom" data-html="true" title="{{ 'thought.chain.added_to_chain'|trans }} {{ include(template)|escape }}">
                    {{ 'thought.chain.already_added'|trans }}
                </span>
            {% endif %}
        </div>

    </div>

    {#  Commentaires  #}
    <div class="quote_row">
        <div class="commentaires">
            {% if thought.comments|length and app.request.get('_route') == 'thought_homepage_index' %}
                <a class="show-link" data-id="{{ thought.id }}">{{ 'thought.comment.quantity_comments'|trans }}: {{ thought.comments|length }}</a>
            {% else %}
                <p>{{ 'thought.comment.quantity_comments'|trans }}: {{ thought.comments|length }}</p>
            {% endif %}

            <div class="comments hidden" data-id="{{ thought.id }}">
                {% for thoughtComments in comments[thought.id] %}
                    {% for comment in thoughtComments %}
                        <p class="profile-link"><a href="">{{ comment.name }}</a></p>
                        <p class="comment-data">{{ comment.createdAt|date('d.m.Y') }}</p>
                        <p>{{ comment.text }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
        {{ include('@Thought/chainSelector.html.twig') }}
    </div>

    <div class="quote_row">
        <div class="owner">
            {% if thought.owner %}
                <span>
                    {{ 'thought.chain.added_to_site'|trans }}
                    <a href="{{ path('user_profile', { 'userId': thought.owner.id } ) }}">
                        {{ thought.owner.firstname }}
                    </a>
                </span>
            {% endif %}
        </div>
        <div>
            {% if chainId is defined %}
                {% if app.user %}
                    {% if already_chains|length %}
                        {% for chainThought in thought.chainThoughts %}
                            {% if chainThought.user != null and chainThought.chain.id == chainId %}
                                <span>
                                    {{ 'thought.chain.added_by'|trans }}
                                    <a href="{{ path('user_profile', { 'userId': chainThought.user.id } ) }}">
                                        {{ chainThought.user.firstname }}
                                    </a>
                                </span>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>

src/ThoughtBundle/Resources/views/thoughtPage.html.twig
{% extends 'ThoughtBundle::layout.html.twig' %}

{% block page_title %}Les fils de la pensée{% endblock %}

{% block content %}

    {% if not app.user %}
        {{ include('@Thought/include/likeModal.html.twig') }}
    {% endif %}

    {{ include('@Thought/quoteLayout.html.twig', {'thought': thought}) }}

    <div class="row block_comments">
        <div class="col-sm-12">
            <h3>{{ 'thought.comment.title'|trans }}</h3>
        </div>
        <div class="col-sm-12">
            {% for comment in thought.comments %}
                <div class="panel panel-info comment-item col-sm-12">
                    <div class="panel-heading row">
                        <div class="col-sm-6">
                            {#<a href="{{ path('user_profile', { 'userId': comment.user.id }) }}">#}
                                {{ comment.fullName }}
                            {#</a>#}
                            {#{{ dump(comment) }}#}
                        </div>
                        <div class="col-sm-6 text-right">
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('thought_thoughtpage_deletecomment', {'commentId': comment.id}) }}">{{ 'user.comment.delete'|trans }}</a>
                            {% endif %}
                            {{ comment.createdAt|date('Y-m-d H:i') }}
                        </div>
                    </div>
                    <div class="panel-body">{{ comment.text|nl2br }}</div>
                </div>
            {% else %}
                {{ 'thought.comment.no_comments'|trans }}
            {% endfor %}
        </div>

        {% set check1 = false %}
        {% set check2 = false %}

        {% if is_granted('ROLE_STUDENT') %}
            {% set check1 = true %}
        {% endif %}

        {% if thought.owner.roles is defined and 'ROLE_STUDENT' in thought.owner.roles %}
            {% set check2 = true %}
        {% endif %}

        {% if check1 == check2 %}
            {% set check = true %}
        {% else %}
            {% set check = false %}
        {% endif %}

        {% if app.user and check %}
            <div class="col-sm-12 col-md-6 form_comments">
                <h3>{{ 'thought.comment.add'|trans }}</h3>
                <form method="post" class="form-horizontal" {{ form_enctype(form) }}>
                    {{ form_errors(form.text) }}
                    {{ form_errors(form.email) }}


                    {{ form_widget(form.name, {'type': 'hidden'}) }}
                    {{ form_widget(form.email, {'type': 'hidden'}) }}

                    <div class="form-group">
                        {{ form_label(form.text) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.text) }}
                        </div>
                    </div>
                    {{ form_rest(form) }}
                    <div class="comment-button-block">
                        <button class="btn btn-info pull-right">{{ 'thought.comment.send_comment'|trans }}</button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/thought/js/quote_functions.js') }}"></script>
    <script>
        $(".related-thoughts-label").click(function () {
            var $this = $(this);
            var $relatedThoughts = $this.next();

            if ($relatedThoughts.is(":hidden")) {
                $relatedThoughts.css('display', 'flex');
            } else {
                $relatedThoughts.hide();
            }

        });
    </script>
{% endblock %}